COMMON: &common
  MAX_CONTENT_LENGTH: 16793600 # 16 MB
  LOGGING: True
  LOG_FILE_PATH: 'logs/'
  LOG_FILE: 'cchecker_web.log'
  HOST: localhost
  PORT: 3000
  DEBUG: True
  UPLOAD_FOLDER: /tmp/datasets
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_DB: 6

  CACHE:
    CACHE_TYPE: simple

DEVELOPMENT: &development
  <<: *common 
  DEBUG: True

PRODUCTION: &production
  <<: *common
  DEBUG: False

