COMMON: &common
  MAX_CONTENT_LENGTH: 16793600 # 16 MB
  LOGGING: True
  LOG_FILE_PATH: 'logs/'
  LOG_FILE: 'cchecker_web.log'
  SECRET_KEY: xxxxxxxxxxx
  HOST: localhost
  PORT: 3000
  DEBUG: True
  UPLOAD_FOLDER: /tmp/datasets
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_DB: 6

  CACHE:
    CACHE_TYPE: simple
    
  MAIL_SERVER: localhost
  MAIL_PORT: 25
  MAIL_USE_TLS: True
  MAIL_USERNAME: localuser
  MAIL_PASSWORD: password
  MAIL_DEFAULT_SENDER: localuser@localhost
  MAIL_ENABLED: False
  MAIL_DEFAULT_TO: 
    - localuser@localhost
  MAILER_DEBUG: False

DEVELOPMENT: &development
  <<: *common 
  DEBUG: True

PRODUCTION: &production
  <<: *common
  DEBUG: False

